---
- name: test playbook
  hosts: all
  tasks:
  - name: install some packages
    apt:
      name:
        - vim
        - cowsay
        - fortune
  - name: set tz
    community.general.timezone:
      name: US/Central

