---
- name: test playbook
  hosts: all
  tasks:
  - name: remove snapd
    apt:
      name: snapd
      state: absent
  - name: install some packages
    apt:
      name:
        - cowsay
        - curl
  - name: set tz
    community.general.timezone:
      name: US/Central

